### ISSUE TITLE
MAX-M10S module from SparkFun works

### ISSUE THREAD

**Issue by awol96** [liamhays/ublox#5]

**Comment by liamhays** [comment]
Is it this product, and did you test every feature? https://www.sparkfun.com/products/18037

**Comment by awol96** [comment]
Yes that is the one I have/purchased from sparkfun. I've gone through and changed all the settings, testing it. The logging works well and syncing the time to GPS returns the correct time and date. 

I am more than happy to further test anything you'd like with this module.

**Comment by liamhays** [comment]
Cool, thank you! Added to the README.

**Comment by jovanoviczmilos** [comment]
I'm testing the same module but getting no data - see the screenshot:
<img width="331" alt="FZ u-blox GPS Screenshot 2024-04-27" src="https://github.com/liamhays/ublox/assets/41778352/7a81e47c-6928-47c7-9c2d-966d4fd8715d">
@awol96 which firmware version you tested with?

**Comment by awol96** [comment]
I use roguemaster and sometimes it can take a bit to get a fix. But currently I'm on the most recent version of RM as of 04/27/2024

**Comment by liamhays** [comment]
@jovanoviczmilos can you open a new issue?
