### ISSUE TITLE
Ublox

### ISSUE THREAD

**Issue by William-i-am** [liamhays/ublox#6]
I have the resent update of Flipper firmware to 1..0.1 and Ublox has stopped working 

Best regards,
William

**Comment by liamhays** [comment]
Can you please describe what's happening in more detail? If possible, can you also add screenshots and log output? (you can get the logs by attaching the Flipper to a computer and reading its serial port).

I currently have my Flipper but not a GPS module, so my ability to test things is limited.

**Comment by William-i-am** [comment]
Howdy,On the iPhone flipper app selection and on flipper it’s say upgrade Ublox. Best regards, William MabeyOn Sep 23, 2024, at 1:41 PM, Liam Hays ***@***.***> wrote:﻿
Can you please describe what's happening in more detail? If possible, can you also add screenshots and log output? (you can get the logs by attaching the Flipper to a computer and reading its serial port).
I currently have my Flipper but not a GPS module, so my ability to test things is limited.

**Comment by liamhays** [comment]
I updated the app from the Flipper app and it runs just fine. Are you using official firmware? Is the app up to date?

**Comment by liamhays** [comment]
Hello, is this still a problem? I would like to close the issue.

**Comment by liamhays** [comment]
No response, closing the issue. If it happens again please open a new issue with detailed information.
